*-------------------------------------------------------------------------------
* MASTER SCRIPT
*
* Replication package for:
*   "A terminated carbon project in Mozambique: underperformance on emissions,
*    persistent local benefits"
*   Journal of Environmental Management
*
* This script reproduces every figure and table in the manuscript and the
* Supplementary Information that is generated by code. See docs/crosswalk.md
* for the mapping from each published figure and table to the script and the
* output file that produces it.
*
* HOW TO RUN
*   1. Download the data archive from Zenodo (DOI in README.md) and unpack it
*      so that the folders data/ and processed/ sit next to this file.
*   2. In Stata, change the working directory to the folder containing this
*      file, then run it:
*          cd "/path/to/replication"
*          do run.do
*      Every path below is relative to that folder, so the package runs from
*      any location on any platform.
*
* OUTPUT
*   results/figures/       figures reported in the manuscript and the SI
*   results/tables/        tables reported in the SI
*   results/diagnostics/   supporting output not reported in the paper
*   results/intermediate/  working .gph panels
*   scripts/logs/          timestamped run log
*
* FOR A CLEAN RUN, delete the following folders before starting:
*   results/
*   (keep processed/ unless you also have the raw data; see the note below)
*
* NOTE ON 01_clean_data.do
*   This script is shipped for transparency but is NOT executed below. It
*   requires the raw household survey, which contains respondent names, phone
*   numbers and GPS coordinates and is therefore not distributed. The pipeline
*   starts from the de-identified analysis-ready data in processed/. Raw data
*   are available from the authors on request. To re-run the full pipeline
*   including cleaning, obtain the raw data and uncomment the call below.
*-------------------------------------------------------------------------------


*--------------------------------------------------
* Working directory
*--------------------------------------------------
* The package root is the current working directory. Stata has no reliable way
* to detect the path of the running do-file, so we verify the working directory
* instead of guessing it. Every other path in the package is relative to this.
capture confirm file "run.do"
if _rc {
	di as error "Stata's working directory is not the package root."
	di as error "Current directory: `c(pwd)'"
	di as error ""
	di as error "Change to the folder containing run.do and try again, e.g."
	di as error `"    cd "/path/to/replication""'
	di as error `"    do run.do"'
	exit 601
}
global working_ANALYSIS "`c(pwd)'"
di as text "Package root: $working_ANALYSIS"

* Sanity check: the data archive must have been unpacked here.
capture confirm file "processed/hansen20pct_rdy.dta"
if _rc {
	di as error "processed/hansen20pct_rdy.dta not found."
	di as error "Download the data archive from Zenodo (DOI in README.md) and"
	di as error "unpack it so that data/ and processed/ sit next to run.do."
	exit 601
}


*--------------------------------------------------
* Program setup
*--------------------------------------------------
clear all
set more off
capture log close _all

cap mkdir "$working_ANALYSIS/scripts/logs"
local datetime : di %tcCCYY.NN.DD!-HH.MM.SS `=clock("$S_DATE $S_TIME", "DMYhms")'
log using "$working_ANALYSIS/scripts/logs/run_`datetime'.log.txt", text name(mainlog)

di "Begin date and time: $S_DATE $S_TIME"
di "Stata version: `c(stata_version)'"
di "Updated as of: `c(born_date)'"
di "Variant:       `=cond( c(MP),"MP",cond(c(SE),"SE",c(flavor)) )'"
di "Processors:    `c(processors)'"
di "OS:            `c(os)' `c(osdtl)'"
di "Machine type:  `c(machine_type)'"

* The published results were produced under Stata 19 on Windows.
* See docs/software_versions.md for the add-on package versions.
version 19

* Use only the add-on packages vendored with this package, so that the results
* do not depend on whatever versions happen to be installed on this machine.
tokenize `"$S_ADO"', parse(";")
while `"`1'"' != "" {
	if `"`1'"' != "BASE" cap adopath - `"`1'"'
	macro shift
}
adopath ++ "$working_ANALYSIS/scripts/libraries/stata"
mata: mata mlib index
sysdir set PERSONAL "$working_ANALYSIS/scripts/libraries/stata"

* Output directories
cap mkdir "$working_ANALYSIS/processed"
cap mkdir "$working_ANALYSIS/results"
cap mkdir "$working_ANALYSIS/results/intermediate"
cap mkdir "$working_ANALYSIS/results/tables"
cap mkdir "$working_ANALYSIS/results/figures"
cap mkdir "$working_ANALYSIS/results/diagnostics"


*--------------------------------------------------
* Graph style
*--------------------------------------------------
* Suppress on-screen rendering. Graphs are still created, combined and
* exported; only the display step is skipped. This is required for batch runs:
* several scripts combine large map graphs, which is unstable when Stata tries
* to render them to a hidden window.
set graphics off

set scheme tab2
grstyle init
{
* Background
grstyle set color white: background plotregion graphregion legend box textbox

* Font sizes
grstyle set size 10pt: heading
grstyle set size 8pt: subheading axis_title
grstyle set size 8pt: p#label p#boxlabel body small_body text_option axis_label ///
                      tick_label minortick_label key_label
}


*--------------------------------------------------
* Analysis pipeline
*--------------------------------------------------
* Scripts are numbered in execution order. Two ordering constraints matter:
*   - all matching (02-04) must precede the event study (05), which reads the
*     matched datasets for both the Hansen 20% and the miombo samples;
*   - the event study (05) must precede the Hansen 20% DiD (06), which combines
*     the event-study graph as panel C of Figure 4.

* Graphs are saved to disk, but Stata also keeps every one of them in memory.
* The matching scripts each build about twenty graphs, several of them maps with
* over half a million polygon vertices, which is enough to exhaust the graph
* subsystem partway through a full run. Clearing between scripts keeps memory
* flat. Scripts that reuse a graph read it back from results/intermediate/, so
* nothing is lost.

* Data preparation: requires the raw data, not distributed. See the note above.
* do "$working_ANALYSIS/scripts/01_clean_data.do"

* Matching
do "$working_ANALYSIS/scripts/02_matching_hansen20.do"      // primary, 20% canopy
graph drop _all
do "$working_ANALYSIS/scripts/03_matching_hansen30.do"      // robustness, 30% canopy
graph drop _all
do "$working_ANALYSIS/scripts/04_matching_miombo.do"        // SI, own classification
graph drop _all

* Forest cover results
do "$working_ANALYSIS/scripts/05_event_study.do"            // Tables S1, S6; Fig 4C
graph drop _all
do "$working_ANALYSIS/scripts/06_did_hansen20.do"           // Fig 4, S4; Tables S4, S5, S9
graph drop _all
do "$working_ANALYSIS/scripts/07_did_hansen30.do"           // Fig S5; Table S7
graph drop _all
do "$working_ANALYSIS/scripts/08_did_miombo.do"             // Fig S7, S8; Tables S12-S16
graph drop _all

* Robustness and leakage
do "$working_ANALYSIS/scripts/09_matching_sensitivity.do"   // Table S8
graph drop _all
do "$working_ANALYSIS/scripts/10_gnp_leakage.do"            // Fig S6; Table S10
graph drop _all

* Household survey
do "$working_ANALYSIS/scripts/11_survey_analysis.do"        // Fig 5-8, S10, S11; Tables S17, S22-S27
graph drop _all


*--------------------------------------------------
* Done
*--------------------------------------------------
di "End date and time: $S_DATE $S_TIME"
di "RUN_COMPLETE"

log close mainlog

** EOF
